/*



/*SELECCION DE COLUMNAS*/

--1-- 
SELECT 
	EMPNO, ENAME 
FROM SCOTT.EMP; /*NO TIENE COLUMNAS APELLIDO, NI EMAIL*/

--2--
SELECT 
	EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL 
FROM HR.EMPLOYEES;

--3--
SELECT 
	CUR_ID, CUR_NOMBRE, CUR_PRECIO, CUR_PROFESOR 
FROM EDUCA.CURSO;

--4--
SELECT 
	DEPTNO, DNAME 
FROM SCOTT.DEPT;

SELECT 
	DEPARTMENT_ID, DEPARTMENT_NAME 
FROM HR.DEPARTMENTS;

--5--
SELECT 
	CUR_NOMBRE, CUR_VACANTES, CUR_PRECIO 
FROM EDUCA.CURSO;


/*CAMPOS CALCULADOS*/

--1--
SELECT
	CUR_NOMBRE, CUR_MATRICULADOS, ROUND(((CUR_MATRICULADOS*100)/CUR_VACANTES),2) "% MATRICULADOS"
FROM EDUCA.CURSO;

--2--
SELECT
	FIRST_NAME ||' '|| LAST_NAME "NOMBRE Y APELLIDO"
FROM HR.EMPLOYEES; 

--3--
SELECT 
	CUR_NOMBRE, CUR_VACANTES*CUR_PRECIO "IMPORTE TOTAL"
FROM EDUCA.CURSO;

--4--
SELECT
	NOMBRE, PRECIO*STOCK "IMPORTE TOTAL"
FROM VENTAS.PRODUCTO;

--5--
SELECT emp.*, sueldo + NVL (comision,0) TOTAL
FROM recursos.empleado emp;
