
WITH 
V1 AS(
	SELECT IDCARGO, AVG(SUELDO) SUELDPROM
	FROM RECURSOS.EMPLEADO
	GROUP BY IDCARGO
)
SELECT EMP.*, V1.SUELDPROM
FROM RECURSOS.EMPLEADO EMP 
JOIN V1
ON V1.IDCARGO= EMP.IDCARGO
AND EMP.SUELDO < V1.SUELDPROM;