-- INSERT

INSERT INTO SCOTT.EMP( EMPNO, ENAME )
VALUES( 8888, 'PEDRO' );

INSERT INTO SCOTT.EMP( EMPNO, ENAME, HIREDATE )
VALUES( 8881, 'JUAN', TO_DATE('15/01/10','DD/MM/RR') );

COMMIT;


SELECT * FROM SCOTT.EMP 
WHERE EMPNO IN (8888,8881);



INSERT INTO SCOTT.EMP( EMPNO, ENAME, SAL )
SELECT 
  TO_NUMBER(SUBSTR(IDEMPLEADO,-4)), 
  NOMBRE, SUELDO
FROM RECURSOS.EMPLEADO;

COMMIT;

SELECT * FROM SCOTT.EMP 